// ─────────────────────────────────────────────────────────────
// enrich.mjs — Catalog → AI-ready feed transformer
//
// This is the heart of the "AI Commerce Enablement Layer": it takes a
// thin, traditional product catalog and upgrades every product with the
// fields AI agents and shopping feeds require — brand, GTIN/MPN,
// availability, inventory, variants (size/color), material and a Google
// product category. Output overwrites products.json (the feed).
//
// Run:  node tools/enrich.mjs
// ─────────────────────────────────────────────────────────────
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const products = JSON.parse(await readFile(join(ROOT, 'products.json'), 'utf8'));

// ── Per-product attributes the traditional catalog didn't carry ──
// (brand, dominant colour and material — the things a shopper or agent
//  filters on). Keyed by product id.
const ATTR = {
  1:  { brand: 'Nike',            color: 'Blue',        material: 'Mesh' },
  2:  { brand: 'Adidas',          color: 'White',       material: 'Leather' },
  3:  { brand: 'Converse',        color: 'Black',       material: 'Canvas' },
  4:  { brand: 'New Balance',     color: 'Grey',        material: 'Suede' },
  5:  { brand: 'Vans',            color: 'Black',       material: 'Canvas' },
  6:  { brand: 'Nike',            color: 'Cyan',        material: 'Flyknit' },
  7:  { brand: 'Adidas',          color: 'Core Black',  material: 'Primeknit' },
  8:  { brand: 'Brooks',          color: 'Green',       material: 'Engineered Mesh' },
  9:  { brand: 'ASICS',           color: 'Purple',      material: 'Jacquard Mesh' },
  10: { brand: 'Timberland',      color: 'Wheat',       material: 'Full-grain Leather' },
  11: { brand: 'Dr. Martens',     color: 'Black',       material: 'Smooth Leather' },
  12: { brand: 'Thursday Boot Co.', color: 'Brown',     material: 'Full-grain Leather' },
  13: { brand: 'Birkenstock',     color: 'Brown',       material: 'Cork & Suede' },
  14: { brand: 'Teva',            color: 'Black',       material: 'Recycled Webbing' },
  15: { brand: 'Reef',            color: 'Black',       material: 'Recycled PET' },
};

// All products here are footwear → one Google taxonomy node.
// Apparel & Accessories > Shoes
const GOOGLE_CATEGORY = '187';
const SIZES = [7, 8, 9, 10, 11, 12]; // US sizes offered for every model

// ── EAN-13 check digit (so GTINs are structurally valid) ─────
function ean13(body12) {
  const d = body12.split('').map(Number);
  const sum = d.reduce((s, n, i) => s + n * (i % 2 === 0 ? 1 : 3), 0);
  const check = (10 - (sum % 10)) % 10;
  return body12 + check;
}

const enriched = products.map((p) => {
  const a = ATTR[p.id] || { brand: 'Generic', color: 'Multi', material: 'Synthetic' };
  const mpn = `${a.brand.replace(/[^A-Za-z0-9]/g, '').toUpperCase().slice(0, 6)}-${String(
    p.id
  ).padStart(4, '0')}`;

  // One GTIN per size variant; deterministic so re-running is stable.
  const variants = SIZES.map((size, i) => {
    const gtin = ean13(`200${String(p.id).padStart(4, '0')}${String(size).padStart(2, '0')}0`.slice(0, 12).padEnd(12, '0'));
    const inventory = ((p.id * 7 + size * 3) % 40) + 3; // 3..42, deterministic
    return {
      size: `US ${size}`,
      color: a.color,
      sku: `SKU-${p.id}-${size}`,
      gtin,
      availability: inventory > 0 ? 'in_stock' : 'out_of_stock',
      inventory_quantity: inventory,
    };
  });

  const totalInventory = variants.reduce((s, v) => s + v.inventory_quantity, 0);

  return {
    ...p,
    brand: a.brand,
    mpn,
    gtin: variants[0].gtin,
    condition: 'new',
    color: a.color,
    material: a.material,
    availability: totalInventory > 0 ? 'in_stock' : 'out_of_stock',
    inventory_quantity: totalInventory,
    google_product_category: GOOGLE_CATEGORY,
    item_group_id: `GRP-${p.id}`,
    sizes: SIZES.map((s) => `US ${s}`),
    variants,
    images: [p.image],
  };
});

await writeFile(join(ROOT, 'products.json'), JSON.stringify(enriched, null, 2) + '\n');

// Keep data.js (used by the site + the browser discovery demo) in sync,
// so the whole front-end runs on the same enriched catalog.
const dataJs =
  `// Auto-generated by tools/enrich.mjs — do not edit by hand.\n` +
  `// Source of truth is products.json (regenerate with: node tools/enrich.mjs).\n` +
  `const PRODUCTS = ${JSON.stringify(enriched, null, 2)};\n\n` +
  `const CATEGORIES = [...new Set(PRODUCTS.map(p => p.category))];\n`;
await writeFile(join(ROOT, 'data.js'), dataJs);

const fields = Object.keys(enriched[0]).length;
console.log(`✓ Enriched ${enriched.length} products → products.json + data.js`);
console.log(`  ${fields} fields each (was 7): brand, mpn, gtin, condition, color,`);
console.log(`  material, availability, inventory, google_product_category, variants…`);
console.log(`  ${enriched.length * SIZES.length} size variants generated with valid EAN-13 GTINs.`);
console.log('\nNext: node tools/build-seo.mjs');
